import { SlideData, TextConfig } from '@/components/LinkedInCarouselTemplate';

const defaultConfig: TextConfig = { visible: true, align: 'center' };
const leftConfig: TextConfig = { visible: true, align: 'left' };
const hiddenConfig: TextConfig = { visible: false, align: 'center' };

export const templates: Record<string, SlideData[]> = {
  default_blank: [
    {
      id: 1,
      type: 'hook',
      imageUrl: null,
      text: '',
      headline: 'Enter Headline',
      subheadline: 'Enter Subheadline',
      eyebrowConfig: hiddenConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: defaultConfig,
      bodyConfig: hiddenConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'center',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    },
    {
      id: 2,
      type: 'thesis',
      imageUrl: null,
      text: '',
      eyebrow: '01 / The Status Quo',
      headline: 'Enter Thesis',
      body: 'Enter body copy here.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'left',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    },
    {
      id: 3,
      type: 'solution',
      imageUrl: null,
      text: '',
      eyebrow: '02 / The Solution',
      headline: 'Enter Solution',
      body: 'Detail the solution here.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'left',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    },
    {
      id: 4,
      type: 'validation',
      imageUrl: null,
      text: '',
      eyebrow: '03 / Validation',
      subheadline: '100%',
      headline: 'Enter Validation Metric',
      body: 'Enter contextual details',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: leftConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'left',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    },
    {
      id: 5,
      type: 'cta',
      imageUrl: null,
      text: '',
      headline: 'Action Required',
      body: 'Enter CTA details.',
      cta: 'Get Started',
      eyebrowConfig: hiddenConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: defaultConfig,
      ctaConfig: defaultConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'center',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    }
  ],
  institutional_core: [
    {
      id: 10,
      type: 'hook',
      imageUrl: null,
      text: '',
      headline: 'The Next Generation of Private Credit',
      subheadline: 'Architecting dynamic capital solutions.',
      eyebrowConfig: hiddenConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: leftConfig,
      bodyConfig: hiddenConfig,
      ctaConfig: leftConfig,
      footerConfig: hiddenConfig,
      cta: 'Explore Solutions',
      backgroundColorToken: 'gradient-institutional',
      layoutToken: 'left',
      cardVariantToken: 'none',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'overlay-gradient-institutional',
      buttonStyleToken: 'white-solid'
    },
    {
      id: 11,
      type: 'thesis',
      imageUrl: null,
      text: '',
      eyebrow: '01 / The Status Quo',
      headline: 'Static capital structures inhibit agility.',
      body: 'Legacy private credit markets are burdened by opaque, slow-moving administrative systems that lock capital for prolonged periods and lack real-time visibility.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'light',
      layoutToken: 'left',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'white-solid'
    },
    {
      id: 12,
      type: 'solution',
      imageUrl: null,
      text: '',
      eyebrow: '02 / Bridge2Partners',
      headline: 'Real-time liquidity routing for the C-Suite.',
      body: 'We engineer compliance-first orchestration engines to securely un-silo tier-1 data and enable programmable dynamic routing.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'light',
      layoutToken: 'left',
      cardVariantToken: 'thin-frame',
      headlineColorToken: 'text-primary',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'cutout',
      buttonStyleToken: 'white-solid'
    },
    {
      id: 13,
      type: 'validation',
      imageUrl: null,
      text: '',
      eyebrow: '03 / Validation',
      subheadline: '85%',
      headline: 'of institutional wealth managers prioritize dynamic execution.',
      body: 'Adaptability is the primary mechanism for defending basis points in volatile markets.',
      footer: 'Source: 2026 Internal Tier-1 Banking Study',
      eyebrowConfig: defaultConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: defaultConfig,
      bodyConfig: defaultConfig,
      ctaConfig: hiddenConfig,
      footerConfig: defaultConfig,
      backgroundColorToken: 'dark',
      layoutToken: 'center',
      cardVariantToken: 'none',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'none',
      buttonStyleToken: 'white-solid'
    },
    {
      id: 14,
      type: 'cta',
      imageUrl: null,
      text: '',
      headline: 'Secure Your Infrastructure.',
      subheadline: 'Architecting alpha through unified ledgers.',
      cta: 'Read the Whitepaper',
      eyebrowConfig: hiddenConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: defaultConfig,
      bodyConfig: hiddenConfig,
      ctaConfig: defaultConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'gradient-radial-brand',
      layoutToken: 'center',
      cardVariantToken: 'understated-solid',
      headlineColorToken: 'text-dark',
      bodyColorToken: 'text-neutral',
      imageStyleToken: 'none',
      buttonStyleToken: 'teal-solid'
    }
  ],
  aurora_social_launch: [
    {
      id: 20,
      type: 'hook',
      imageUrl: null,
      text: '',
      headline: 'Unlock Total Market Liquidity.',
      subheadline: 'Bypass legacy ledgers today.',
      cta: 'View Live Data',
      eyebrowConfig: hiddenConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: defaultConfig,
      bodyConfig: hiddenConfig,
      ctaConfig: defaultConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'bg-aurora-spots',
      layoutToken: 'center',
      cardVariantToken: 'none',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'overlay-aurora-spots',
      buttonStyleToken: 'frosted-outline'
    },
    {
      id: 21,
      type: 'thesis',
      imageUrl: null,
      text: '',
      eyebrow: '01 / The Fragmentation Problem',
      headline: 'Trillions are siloed.',
      body: 'Current wealth infrastructure cannot seamlessly track modern diverse asset portfolios.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'bg-aurora-spots',
      layoutToken: 'left',
      cardVariantToken: 'thin-frame',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'none',
      buttonStyleToken: 'frosted-outline'
    },
    {
      id: 22,
      type: 'solution',
      imageUrl: null,
      text: '',
      eyebrow: '02 / Centralized Truth',
      headline: 'A unified programmable ledger.',
      body: 'Bridge2Partners establishes a unified golden record synced instantaneously across global counterparties.',
      eyebrowConfig: leftConfig,
      headlineConfig: leftConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: leftConfig,
      ctaConfig: hiddenConfig,
      footerConfig: hiddenConfig,
      backgroundColorToken: 'bg-aurora-spots',
      layoutToken: 'left',
      cardVariantToken: 'none',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'framed',
      buttonStyleToken: 'frosted-outline'
    },
    {
      id: 23,
      type: 'validation',
      imageUrl: null,
      text: '',
      eyebrow: '03 / Speed to Market',
      subheadline: 'T+0',
      headline: 'Instant settlement. Zero friction.',
      body: 'Immediate atomic execution eliminates counterparty risk instantly.',
      footer: 'Bridge2Partners Internal Data',
      eyebrowConfig: defaultConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: defaultConfig,
      bodyConfig: defaultConfig,
      ctaConfig: hiddenConfig,
      footerConfig: defaultConfig,
      backgroundColorToken: 'bg-aurora-spots',
      layoutToken: 'center',
      cardVariantToken: 'thin-frame',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'none',
      buttonStyleToken: 'frosted-outline'
    },
    {
      id: 24,
      type: 'cta',
      imageUrl: null,
      text: '',
      headline: 'Ready to Upgrade?',
      subheadline: 'Request a Demo Workspace',
      cta: 'Initialize Platform',
      eyebrowConfig: hiddenConfig,
      headlineConfig: defaultConfig,
      subheadlineConfig: hiddenConfig,
      bodyConfig: hiddenConfig,
      ctaConfig: defaultConfig,
      footerConfig: defaultConfig,
      backgroundColorToken: 'bg-aurora-spots',
      layoutToken: 'center',
      cardVariantToken: 'none',
      headlineColorToken: 'text-light',
      bodyColorToken: 'text-light',
      imageStyleToken: 'none',
      buttonStyleToken: 'frosted-outline'
    }
  ]
};
